[phases.setup]
nixPkgs = [
    "php83",
    "php83Packages.composer",
    "php83Extensions.pdo",
    "php83Extensions.pdo_mysql",
    "php83Extensions.mbstring",
    "php83Extensions.xml",
    "php83Extensions.curl",
    "php83Extensions.tokenizer",
    "nodejs"
]

[phases.install]
cmds = [
    "composer install --ignore-platform-reqs --no-scripts",
    "npm i"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts"]
